apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: inception-app-deployment
spec:
  template:
    metadata:
      labels:
        app: inception-app
    spec:
      containers:
      - name: inception-app-container
        image: abhishek/inception
        imagePullPolicy: "IfNotPresent"
        command:
        - /bin/sh
        - -c
        args:
        - cd tensorflow-app/pet && node app.js --inception_client=/inception_client/inception_client --server=10.254.35.139:9000
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: inception-app
  name: inception-app
spec:
  ports:
  - port: 3000
  selector:
    app: inception-app
  externalIPs: [192.168.122.66]
